// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using AutoMapper;
using Microsoft.Extensions.Logging;
using CodeCraft.NET.Application.Contracts.Persistence;
using CodeCraft.NET.Application.CQRS.Base.Features;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Features.LogSummaries.Commands.Update;

internal partial class LogSummaryUpdateHandler : UpdateHandler<LogSummaryUpdate, LogSummary, ICodeCraftUnitOfWork>
{
	public LogSummaryUpdateHandler(ICodeCraftUnitOfWork unitOfWork, IMapper mapper, ILogger<LogSummaryUpdateHandler> logger)
		: base(unitOfWork, mapper, logger)
	{
	}
}