// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using System;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Features.LogSummaries.Commands.Update;

public partial class LogSummaryUpdate : IRequest<bool>
{
    public DateTime SummaryDate { get; set; }
    public string Component { get; set; }
    public int DebugCount { get; set; }
    public int InfoCount { get; set; }
    public int WarningCount { get; set; }
    public int ErrorCount { get; set; }
    public int CriticalCount { get; set; }
    public int TotalCount { get; set; }
    public long TotalSizeBytes { get; set; }
    public double? AverageResponseTimeMs { get; set; }
    public int UniqueUsersCount { get; set; }
    public int UniqueSessionsCount { get; set; }
    public DateTime? FirstOccurrence { get; set; }
    public DateTime? LastOccurrence { get; set; }
    public string TopCategories { get; set; }
    public string TopErrors { get; set; }
    public string Notes { get; set; }
    public int Id { get; set; }
    public bool Active { get; set; }
    public DateTime CreatedOn { get; set; }
    public string CreatedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
    public string ModifiedBy { get; set; }
}