// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using FluentValidation;
using CodeCraft.NET.Application.CQRS.Base.Features;
using CodeCraft.NET.Application.CQRS.Features.LogSummaries.Commands.Update;

namespace CodeCraft.NET.Application.CQRS.Features.LogSummaries.Validators
{
    public partial class LogSummaryUpdateValidator : BaseValidator<LogSummaryUpdate>
    {
        public LogSummaryUpdateValidator()
        {
            RuleFor(x => x.Id).GreaterThan(0);
            RuleFor(x => x.SummaryDate).NotEmpty();
            RuleFor(x => x.Component).NotEmpty();
            RuleFor(x => x.DebugCount).GreaterThan(0);
            RuleFor(x => x.InfoCount).GreaterThan(0);
            RuleFor(x => x.WarningCount).GreaterThan(0);
            RuleFor(x => x.ErrorCount).GreaterThan(0);
            RuleFor(x => x.CriticalCount).GreaterThan(0);
            RuleFor(x => x.TotalCount).GreaterThan(0);
            RuleFor(x => x.TotalSizeBytes).GreaterThan(0);
            RuleFor(x => x.UniqueUsersCount).GreaterThan(0);
            RuleFor(x => x.UniqueSessionsCount).GreaterThan(0);
            RuleFor(x => x.TopCategories).NotEmpty();
            RuleFor(x => x.TopErrors).NotEmpty();
            RuleFor(x => x.Notes).NotEmpty();
            RuleFor(x => x.CreatedOn).NotEmpty();
            RuleFor(x => x.CreatedBy).NotEmpty();
            RuleFor(x => x.ModifiedBy).NotEmpty();
        }
    }
}
