// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using CodeCraft.NET.Application.DTOs.LogConfigurations;

namespace CodeCraft.NET.Application.CQRS.Features.LogConfigurations.Queries.GetLogConfigurationById
{
	public partial class GetLogConfigurationByIdQuery : IRequest<LogConfigurationDto?>
	{
		public int Id { get; set; }
	}
}