// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using CodeCraft.NET.Application.DTOs.Custom.LogConfigurations;

namespace CodeCraft.NET.Application.CQRS.Features.LogConfigurations.Queries.GetLogConfigurationWithRelated
{
	public class GetLogConfigurationWithRelatedQuery : IRequest<LogConfigurationWithRelatedDto?>
	{
		public int Id { get; set; }
	}
}