// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using AutoMapper;
using CodeCraft.NET.Application.DTOs.Custom.LogConfigurations;
using CodeCraft.NET.Domain.Model;
using CodeCraft.NET.Application.Contracts.Persistence.Repositories;
using CodeCraft.NET.Application.CQRS.Specifications.LogConfigurations;

namespace CodeCraft.NET.Application.CQRS.Features.LogConfigurations.Queries.GetLogConfigurationWithRelated
{
	public class GetLogConfigurationWithRelatedHandler : IRequestHandler<GetLogConfigurationWithRelatedQuery, LogConfigurationWithRelatedDto?>
	{
		private readonly ILogConfigurationRepository _repository;
		private readonly IMapper _mapper;

		public GetLogConfigurationWithRelatedHandler(ILogConfigurationRepository repository, IMapper mapper)
		{
			_repository = repository;
			_mapper = mapper;
		}

		public async Task<LogConfigurationWithRelatedDto?> Handle(GetLogConfigurationWithRelatedQuery request, CancellationToken cancellationToken)
		{
			var spec = new LogConfigurationWithRelatedSpecification(new LogConfigurationSpecificationParams { Id = request.Id });
			var entity = await _repository.GetByIdWithSpecifications(spec);
			if (entity == null)
				return null;

			return _mapper.Map<LogConfigurationWithRelatedDto>(entity);
		}
	}
}