services:
  postgres:
    image: postgres:15-alpine
    container_name: codecraft-postgres
    environment:
      POSTGRES_DB: CodeCraftDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourStrong(!)Password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - codecraft-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CodeCraftDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: codecraft-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@codecraft.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - codecraft-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:

networks:
  codecraft-network:
    driver: bridge