// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using FluentValidation;
using CodeCraft.NET.Application.CQRS.Base.Features;

namespace CodeCraft.NET.Application.CQRS.Features.LogConfigurations.Commands.Create
{
    public partial class LogConfigurationCreateValidator : AbstractValidator<LogConfigurationCreate>
    {
        public LogConfigurationCreateValidator()
        {
            RuleFor(x => x.Component).NotEmpty();
            RuleFor(x => x.NamespacePath).NotEmpty();
            RuleFor(x => x.LogFilePath).NotEmpty();
            RuleFor(x => x.LogFormat).NotEmpty();
            RuleFor(x => x.RetentionDays).GreaterThan(0);
            RuleFor(x => x.MaxFileSizeMB).GreaterThan(0);
            RuleFor(x => x.Description).NotEmpty();
            RuleFor(x => x.Priority).GreaterThan(0);
            RuleFor(x => x.CreatedOn).NotEmpty();
            RuleFor(x => x.CreatedBy).NotEmpty();
            RuleFor(x => x.ModifiedBy).NotEmpty();
        }
    }
}
