// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;

namespace CodeCraft.NET.Infrastructure.Persistence.Factories
{
    public class ApplicationDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
    {
        public ApplicationDbContext CreateDbContext(string[] args)
        {
            var basePath = Directory.GetCurrentDirectory();

            var serverConfigPath = Path.Combine(basePath, "../CodeCraft.NET.WebAPI/appsettings.json");
            var localConfigPath = Path.Combine(basePath, "appsettings.json");

            IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(basePath)
                .AddJsonFile(File.Exists(localConfigPath) ? "appsettings.json" : serverConfigPath, optional: true)
                .AddEnvironmentVariables()
                .Build();

            var connectionString =
                configuration["ConnectionStrings:Default"] ??
                configuration["DEFAULT_CONNECTION_STRING"] ??
                configuration["ConnectionStrings:Application"] ??
                configuration["APPLICATION_CONNECTION_STRING"];

            if (string.IsNullOrWhiteSpace(connectionString))
                connectionString = "Server=(localdb)\\mssqllocaldb;Database=CodeCraftDb;Trusted_Connection=true;MultipleActiveResultSets=true;";

            var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
            optionsBuilder.UseSqlServer(connectionString);

            return new ApplicationDbContext(optionsBuilder.Options);
        }
    }
}