// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using CodeCraft.NET.Application.DTOs.LogEntries;

namespace CodeCraft.NET.Application.CQRS.Features.LogEntries.Queries.GetLogEntryById
{
	public partial class GetLogEntryByIdQuery : IRequest<LogEntryDto?>
	{
		public int Id { get; set; }
	}
}