// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using AutoMapper;
using CodeCraft.NET.Application.DTOs.Custom.LogEntries;
using CodeCraft.NET.Domain.Model;
using CodeCraft.NET.Application.Contracts.Persistence.Repositories;
using CodeCraft.NET.Application.CQRS.Specifications.LogEntries;

namespace CodeCraft.NET.Application.CQRS.Features.LogEntries.Queries.GetLogEntryWithRelated
{
	public class GetLogEntryWithRelatedHandler : IRequestHandler<GetLogEntryWithRelatedQuery, LogEntryWithRelatedDto?>
	{
		private readonly ILogEntryRepository _repository;
		private readonly IMapper _mapper;

		public GetLogEntryWithRelatedHandler(ILogEntryRepository repository, IMapper mapper)
		{
			_repository = repository;
			_mapper = mapper;
		}

		public async Task<LogEntryWithRelatedDto?> Handle(GetLogEntryWithRelatedQuery request, CancellationToken cancellationToken)
		{
			var spec = new LogEntryWithRelatedSpecification(new LogEntrySpecificationParams { Id = request.Id });
			var entity = await _repository.GetByIdWithSpecifications(spec);
			if (entity == null)
				return null;

			return _mapper.Map<LogEntryWithRelatedDto>(entity);
		}
	}
}