// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using AutoMapper;
using CodeCraft.NET.Application.Contracts.Persistence.Repositories;
using CodeCraft.NET.Application.DTOs.LogEntries;
using CodeCraft.NET.Domain.Model;
using CodeCraft.NET.Application.Middleware.Exceptions;

namespace CodeCraft.NET.Application.CQRS.Features.LogEntries.Queries.GetLogEntryById
{
	public partial class GetLogEntryByIdHandler : IRequestHandler<GetLogEntryByIdQuery, LogEntryDto?>
	{
		private readonly ILogEntryRepository _repository;
		private readonly IMapper _mapper;

		public GetLogEntryByIdHandler(ILogEntryRepository repository, IMapper mapper)
		{
			_repository = repository;
			_mapper = mapper;
		}

		public async Task<LogEntryDto?> Handle(GetLogEntryByIdQuery request, CancellationToken cancellationToken)
		{
			var entity = await _repository.GetByIdAsync(request.Id);
			if (entity == null)
				return null;

			return _mapper.Map<LogEntryDto>(entity);
		}
	}
}
