// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using CodeCraft.NET.Application.DTOs.Custom.LogEntries;

namespace CodeCraft.NET.Application.CQRS.Features.LogEntries.Queries.GetLogEntryWithRelated
{
	public class GetLogEntryWithRelatedQuery : IRequest<LogEntryWithRelatedDto?>
	{
		public int Id { get; set; }
	}
}