/ <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using System.Collections;
using Microsoft.EntityFrameworkCore;
using CodeCraft.NET.Cross.Domain;
using CodeCraft.NET.Application.Contracts.Persistence;
using CodeCraft.NET.Application.Contracts.Persistence.Repositories;
using Infrastructure.Persistence.Repositories;
using CodeCraft.NET.Application.Contracts.Persistence.Base;

namespace Infrastructure.Persistence;

public partial class  : IUnitOfWork
{
    private Hashtable _repositories;
    private readonly ApplicationDbContext _context;

    private IUserRepository _UserRepository { get; set; }
    public IUserRepository UserRepository => _UserRepository ??= new UserRepository(_context);

	public async Task<int> Complete()
    {
        try
        {
            return await _context.SaveChangesAsync();
        }
		catch (DbUpdateException ex)
		{
			throw new Exception("Error saving changes to the database", ex);
		}
		catch (Exception ex)
        {
			throw new Exception("Unexpected error when running UnitOfWork", ex);
		}
	}

    public void Dispose()
    {
        _context.Dispose();
    }

    public IAsyncRepository<TEntity> Repository<TEntity>() where TEntity : BaseDomainModel
    {
        _repositories ??= [];

        string type = typeof(TEntity).Name;

        if (!_repositories.ContainsKey(type))
        {
            Type repositoryType = typeof(RepositoryBase<,>);
            object? repositoryInstance = Activator.CreateInstance(repositoryType.MakeGenericType(typeof(TEntity)), _context);
            _repositories.Add(type, repositoryInstance);
        }

        return (IAsyncRepository<TEntity>)_repositories[type];
    }
}
