// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using AutoMapper;
using CodeCraft.NET.Application.Contracts.Persistence;
using CodeCraft.NET.Application.CQRS.Base.Features;
using CodeCraft.NET.Domain.Model;
using Microsoft.Extensions.Logging;

namespace CodeCraft.NET.Application.CQRS.Features.LogEntries.Commands.Create;

internal partial class LogEntryCreateHandler : CreateHandler<LogEntryCreate, LogEntry, ICodeCraftUnitOfWork>
{
	public LogEntryCreateHandler(ICodeCraftUnitOfWork unitOfWork, IMapper mapper, ILogger<LogEntryCreateHandler> logger)
		: base(unitOfWork, mapper, logger)
	{
	}
}