// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using CodeCraft.NET.Application.DTOs.Custom.LogSummaries;

namespace CodeCraft.NET.Application.CQRS.Features.LogSummaries.Queries.GetLogSummaryWithRelated
{
	public class GetLogSummaryWithRelatedQuery : IRequest<LogSummaryWithRelatedDto?>
	{
		public int Id { get; set; }
	}
}