// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using CodeCraft.NET.Application.DTOs.LogSummaries;

namespace CodeCraft.NET.Application.CQRS.Features.LogSummaries.Queries.GetLogSummaryById
{
	public partial class GetLogSummaryByIdQuery : IRequest<LogSummaryDto?>
	{
		public int Id { get; set; }
	}
}