// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using AutoMapper;
using CodeCraft.NET.Application.Contracts.Persistence.Repositories;
using CodeCraft.NET.Application.DTOs.LogSummaries;
using CodeCraft.NET.Domain.Model;
using CodeCraft.NET.Application.Middleware.Exceptions;

namespace CodeCraft.NET.Application.CQRS.Features.LogSummaries.Queries.GetLogSummaryById
{
	public partial class GetLogSummaryByIdHandler : IRequestHandler<GetLogSummaryByIdQuery, LogSummaryDto?>
	{
		private readonly ILogSummaryRepository _repository;
		private readonly IMapper _mapper;

		public GetLogSummaryByIdHandler(ILogSummaryRepository repository, IMapper mapper)
		{
			_repository = repository;
			_mapper = mapper;
		}

		public async Task<LogSummaryDto?> Handle(GetLogSummaryByIdQuery request, CancellationToken cancellationToken)
		{
			var entity = await _repository.GetByIdAsync(request.Id);
			if (entity == null)
				return null;

			return _mapper.Map<LogSummaryDto>(entity);
		}
	}
}
