// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Application.CQRS.Base.Specifications;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Specifications.Users;

public partial class UserWithRelatedSpecification : BaseSpecification<User>
{
    public UserWithRelatedSpecification(UserSpecificationParams parameters)
        : base(x =>
            string.IsNullOrWhiteSpace(parameters.Search)
                || (x.Email != null && x.Email.ToLower().Contains(parameters.Search.ToLower()))
                || (x.FullName != null && x.FullName.ToLower().Contains(parameters.Search.ToLower()))
                || (x.IdentityId != null && x.IdentityId.ToLower().Contains(parameters.Search.ToLower()))
                || (x.CreatedBy != null && x.CreatedBy.ToLower().Contains(parameters.Search.ToLower()))
                || (x.LastModifiedBy != null && x.LastModifiedBy.ToLower().Contains(parameters.Search.ToLower()))
        )
    {
        Paging(parameters.PageSize * (parameters.PageIndex - 1), parameters.PageSize);

        if (!string.IsNullOrEmpty(parameters.Sort))
        {
            switch (parameters.Sort.ToLower())
            {
                case "idAsc":
                    AddOrderBy(x => x.Id);
                    break;
                case "idDesc":
                    AddOrderByDescending(x => x.Id);
                    break;
                default:
                    AddOrderBy(x => x.Id);
                    break;
            }
        }

    }
}
