// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Application.CQRS.Base.Specifications;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Specifications.Users;

public partial class UserWithRelated : BaseSpecification<User>
{
    public UserWithRelated()
    {
    }
}
