// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using System;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Features.LogConfigurations.Commands.Update;

public partial class LogConfigurationUpdate : IRequest<bool>
{
    public string Component { get; set; }
    public string NamespacePath { get; set; }
    public bool IsEnabled { get; set; }
    public bool LogToDatabase { get; set; }
    public bool LogToFile { get; set; }
    public bool LogToConsole { get; set; }
    public string LogFilePath { get; set; }
    public string LogFormat { get; set; }
    public int RetentionDays { get; set; }
    public int MaxFileSizeMB { get; set; }
    public string Description { get; set; }
    public int Priority { get; set; }
    public int Id { get; set; }
    public bool Active { get; set; }
    public DateTime CreatedOn { get; set; }
    public string CreatedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
    public string ModifiedBy { get; set; }
}