// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using CodeCraft.NET.Application.Contracts.Persistence.Repositories;
using CodeCraft.NET.Domain.Model;
using CodeCraft.NET.Application.Middleware.Exceptions;

namespace CodeCraft.NET.Application.CQRS.Features.Users.Queries.GetUserById
{
	public partial class GetUserByIdHandler : IRequestHandler<GetUserByIdQuery, User>
	{
		private readonly IUserRepository _repository;

		public GetUserByIdHandler(IUserRepository repository)
		{
			_repository = repository;
		}

		public async Task<User> Handle(GetUserByIdQuery request, CancellationToken cancellationToken)
		{
			var config = await _repository.GetByIdAsync(request.Id);
			if (config == null)
				throw new NotFoundException(nameof(User), request.Id);

			return config;
		}
	}
}
