// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Features.Users.Queries.GetUserWithRelated;

public class GetUserWithRelatedQuery : IRequest<User>
{
    public int Id { get; set; }
}