// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using CodeCraft.NET.Services.Services;
using CodeCraft.NET.Services.Services;
using CodeCraft.NET.Services.Services;

namespace CodeCraft.NET.Services
{
    /// <summary>
    /// Service registration for the Services layer.
    /// This file is auto-generated and contains all entity services registration.
    /// </summary>
    public static class ServicesServiceRegistration
    {
        /// <summary>
        /// Registers all Services layer dependencies.
        /// </summary>
        /// <param name="services">The service collection to add services to</param>
        /// <param name="configuration">The configuration instance</param>
        /// <returns>The service collection for chaining</returns>
        public static IServiceCollection AddServicesLayer(this IServiceCollection services, IConfiguration configuration)
        {
            // Register all entity services
            services.AddScoped<LogConfigurationService>();
            services.AddScoped<LogEntryService>();
            services.AddScoped<LogSummaryService>();
            
            return services;
        }
    }
}