// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Application.Contracts.Persistence.Base;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.Contracts.Persistence.Repositories
{
    public partial interface ILogConfigurationRepository : IAsyncRepository<LogConfiguration>
    {
	}
}