// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using AutoMapper;
using CodeCraft.NET.Application.Contracts.Persistence;
using CodeCraft.NET.Application.Contracts.Persistence.Repositories;
using CodeCraft.NET.Application.CQRS.Features.LogSummaries.Commands.Update;
using CodeCraft.NET.Application.Middleware.Exceptions;
using CodeCraft.NET.Domain.Model;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;


namespace CodeCraft.NET.Test.Application.CQRS.Features.LogSummaries.Commands.Update
{
    [TestClass]
    public class LogSummaryUpdateHandlerTests
    {
        private Mock<ILogSummaryRepository> _repositoryMock = null!;
        private Mock<ICodeCraftUnitOfWork> _unitOfWorkMock = null!;
        private Mock<IMapper> _mapperMock = null!;
        private Mock<ILogger<LogSummaryUpdateHandler>> _loggerMock = null!;
        private LogSummaryUpdateHandler _handler = null!;

        [TestInitialize]
        public void Setup()
        {
            _repositoryMock = new Mock<ILogSummaryRepository>();
            _unitOfWorkMock = new Mock<ICodeCraftUnitOfWork>();
            _mapperMock = new Mock<IMapper>();
            _loggerMock = new Mock<ILogger<LogSummaryUpdateHandler>>();

            // Setup specific repository property
            _unitOfWorkMock.Setup(x => x.LogSummaryRepository)
                .Returns(_repositoryMock.Object);

            // Setup generic Repository<T>() method for base handler compatibility
            _unitOfWorkMock.Setup(x => x.Repository<LogSummary>())
                .Returns(_repositoryMock.Object);

            _handler = new LogSummaryUpdateHandler(_unitOfWorkMock.Object, _mapperMock.Object, _loggerMock.Object);
        }

        [TestCleanup]
        public void Cleanup()
        {
            _repositoryMock.Reset();
            _unitOfWorkMock.Reset();
            _mapperMock.Reset();
            _loggerMock.Reset();
        }

        [TestMethod]
        public async Task Handle_ValidCommand_UpdatesEntityAndReturnsTrue()
        {
            // Arrange
            var command = new LogSummaryUpdate
            {
                Id = 1
                // TODO: Set test properties based on LogSummary entity
            };

            var existingEntity = new LogSummary
            {
                Id = 1
                // TODO: Set test properties based on LogSummary entity  
            };

            _repositoryMock.Setup(x => x.GetByIdAsync(command.Id))
                .ReturnsAsync(existingEntity);

            _mapperMock.Setup(x => x.Map(command, existingEntity, command.GetType(), typeof(LogSummary)))
                .Returns(existingEntity);

            // The base handler uses UpdateEntity() not UpdateAsync()
            _repositoryMock.Setup(x => x.UpdateEntity(It.IsAny<LogSummary>()));

            _unitOfWorkMock.Setup(x => x.Complete())
                .ReturnsAsync(1);

            // Act
            var result = await _handler.Handle(command, CancellationToken.None);

            // Assert
            result.Should().BeTrue();

            _repositoryMock.Verify(x => x.GetByIdAsync(command.Id), Times.Once);
            _mapperMock.Verify(x => x.Map(command, existingEntity, command.GetType(), typeof(LogSummary)), Times.Once);
            _repositoryMock.Verify(x => x.UpdateEntity(It.IsAny<LogSummary>()), Times.Once);
            _unitOfWorkMock.Verify(x => x.Complete(), Times.Once);
        }

        [TestMethod]
        public async Task Handle_EntityNotFound_ThrowsNotFoundException()
        {
            // Arrange
            var command = new LogSummaryUpdate { Id = 999 };

            _repositoryMock.Setup(x => x.GetByIdAsync(command.Id))
                .ReturnsAsync((LogSummary?)null);

            // Act & Assert
            await Assert.ThrowsExceptionAsync<NotFoundException>(() => 
                _handler.Handle(command, CancellationToken.None));

            _repositoryMock.Verify(x => x.GetByIdAsync(command.Id), Times.Once);
            _mapperMock.Verify(x => x.Map(It.IsAny<LogSummaryUpdate>(), It.IsAny<LogSummary>(), It.IsAny<Type>(), It.IsAny<Type>()), Times.Never);
            _repositoryMock.Verify(x => x.UpdateEntity(It.IsAny<LogSummary>()), Times.Never);
            _unitOfWorkMock.Verify(x => x.Complete(), Times.Never);
        }

        [TestMethod]
        public async Task Handle_RepositoryGetByIdThrowsException_PropagatesException()
        {
            // Arrange
            var command = new LogSummaryUpdate { Id = 1 };

            _repositoryMock.Setup(x => x.GetByIdAsync(command.Id))
                .ThrowsAsync(new Exception("Database error"));

            // Act & Assert
            await Assert.ThrowsExceptionAsync<Exception>(() => 
                _handler.Handle(command, CancellationToken.None));

            _repositoryMock.Verify(x => x.GetByIdAsync(command.Id), Times.Once);
        }

        [TestMethod]
        public async Task Handle_RepositoryUpdateThrowsException_PropagatesException()
        {
            // Arrange
            var command = new LogSummaryUpdate { Id = 1 };
            var existingEntity = new LogSummary { Id = 1 };

            _repositoryMock.Setup(x => x.GetByIdAsync(command.Id))
                .ReturnsAsync(existingEntity);

            _mapperMock.Setup(x => x.Map(command, existingEntity, command.GetType(), typeof(LogSummary)))
                .Returns(existingEntity);

            _repositoryMock.Setup(x => x.UpdateEntity(It.IsAny<LogSummary>()))
                .Throws(new Exception("Update failed"));

            // Act & Assert
            await Assert.ThrowsExceptionAsync<Exception>(() => 
                _handler.Handle(command, CancellationToken.None));

            _repositoryMock.Verify(x => x.GetByIdAsync(command.Id), Times.Once);
            _repositoryMock.Verify(x => x.UpdateEntity(It.IsAny<LogSummary>()), Times.Once);
            _unitOfWorkMock.Verify(x => x.Complete(), Times.Never);
        }

        [TestMethod]
        public async Task Handle_CompleteReturnsZero_ThrowsException()
        {
            // Arrange
            var command = new LogSummaryUpdate { Id = 1 };
            var existingEntity = new LogSummary { Id = 1 };

            _repositoryMock.Setup(x => x.GetByIdAsync(command.Id))
                .ReturnsAsync(existingEntity);

            _mapperMock.Setup(x => x.Map(command, existingEntity, command.GetType(), typeof(LogSummary)))
                .Returns(existingEntity);

            _repositoryMock.Setup(x => x.UpdateEntity(It.IsAny<LogSummary>()));

            _unitOfWorkMock.Setup(x => x.Complete())
                .ReturnsAsync(0); // No rows affected - handler should throw exception

            // Act & Assert
            await Assert.ThrowsExceptionAsync<Exception>(() => 
                _handler.Handle(command, CancellationToken.None));

            _repositoryMock.Verify(x => x.GetByIdAsync(command.Id), Times.Once);
            _repositoryMock.Verify(x => x.UpdateEntity(It.IsAny<LogSummary>()), Times.Once);
            _unitOfWorkMock.Verify(x => x.Complete(), Times.Once);
        }
    }
}