// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Application.CQRS.Base.Specifications;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Specifications.LogSummaries;

public partial class LogSummarySpecification : BaseSpecification<LogSummary>
{
    public LogSummarySpecification(LogSummarySpecificationParams parameters)
        : base(x =>
            string.IsNullOrWhiteSpace(parameters.Search) 
            || (x.Component != null && x.Component.ToLower().Contains(parameters.Search.ToLower()))
            || (x.TopCategories != null && x.TopCategories.ToLower().Contains(parameters.Search.ToLower()))
            || (x.TopErrors != null && x.TopErrors.ToLower().Contains(parameters.Search.ToLower()))
            || (x.Notes != null && x.Notes.ToLower().Contains(parameters.Search.ToLower()))
            || (x.CreatedBy != null && x.CreatedBy.ToLower().Contains(parameters.Search.ToLower()))
            || (x.ModifiedBy != null && x.ModifiedBy.ToLower().Contains(parameters.Search.ToLower()))
        )
    {
        Paging(parameters.PageSize * (parameters.PageIndex - 1), parameters.PageSize);

        if (!string.IsNullOrEmpty(parameters.Sort))
        {
            switch (parameters.Sort.ToLower())
            {
                case "idAsc":
                    AddOrderBy(x => x.Id);
                    break;
                case "idDesc":
                    AddOrderByDescending(x => x.Id);
                    break;
                default:
                    AddOrderBy(x => x.Id);
                    break;
            }
        }
    }
}
