// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Application.CQRS.Base.Specifications;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Specifications.LogSummaries;

public partial class LogSummaryWithRelated : BaseSpecification<LogSummary>
{
    public LogSummaryWithRelated()
    {
        AddInclude(x => x.ComponentCategory);
    }
}
