// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Application.Contracts.Persistence.Repositories;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Infrastructure.Persistence.Repositories
{
    public partial class LogEntryRepository : RepositoryBase<LogEntry, ApplicationDbContext>, ILogEntryRepository
	{
        public LogEntryRepository(ApplicationDbContext context) : base(context)
        {
        }
	}
}