// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Infrastructure.Persistence;
using CodeCraft.NET.Application.Contracts.Persistence.Repositories;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Infrastructure.Persistence.Repositories
{
    public partial class UserRepository : RepositoryBase<User, ApplicationDbContext>, IUserRepository
	{
        public UserRepository(ApplicationDbContext context) : base(context)
        {
        }
	}
}