// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using AutoMapper;
using Microsoft.Extensions.Logging;
using CodeCraft.NET.Application.Contracts.Persistence;
using CodeCraft.NET.Application.CQRS.Base.Features;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Features.LogEntries.Commands.Delete;

internal partial class LogEntryDeleteHandler : DeleteHandler<LogEntryDelete, LogEntry, ICodeCraftUnitOfWork>
{
	public LogEntryDeleteHandler(ICodeCraftUnitOfWork unitOfWork, IMapper mapper, ILogger<LogEntryDeleteHandler> logger)
		: base(unitOfWork, mapper, logger)
	{
	}
}