// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using System;

namespace CodeCraft.NET.Application.CQRS.Features.Users.Commands.Update;

public partial class UserUpdate : IRequest<bool>
{
    public string Email { get; set; }
    public string FullName { get; set; }
    public int? OrganizationId { get; set; }
    public string IdentityId { get; set; }
    public int Id { get; set; }
    public DateTime? CreatedDate { get; set; }
    public string CreatedBy { get; set; }
    public DateTime? LastModifiedDate { get; set; }
    public string LastModifiedBy { get; set; }
    public bool Active { get; set; }
}