// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using FluentValidation;
using CodeCraft.NET.Application.CQRS.Base.Features;
using CodeCraft.NET.Application.CQRS.Features.Users.Commands.Update;

namespace CodeCraft.NET.Application.CQRS.Features.Users.Validators
{
    public partial class UserUpdateValidator : BaseValidator<UserUpdate>
    {
        public UserUpdateValidator()
        {
            RuleFor(x => x.Id).GreaterThan(0);
            RuleFor(x => x.Email).NotEmpty();
            RuleFor(x => x.FullName).NotEmpty();
            RuleFor(x => x.IdentityId).NotEmpty();
            RuleFor(x => x.CreatedBy).NotEmpty();
            RuleFor(x => x.LastModifiedBy).NotEmpty();
        }
    }
}
