// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;
using System;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Features.LogEntries.Commands.Update;

public partial class LogEntryUpdate : IRequest<bool>
{
    public DateTime Timestamp { get; set; }
    public string Message { get; set; }
    public string Category { get; set; }
    public string Component { get; set; }
    public string Exception { get; set; }
    public string StackTrace { get; set; }
    public string AdditionalData { get; set; }
    public string CorrelationId { get; set; }
    public string SessionId { get; set; }
    public string UserId { get; set; }
    public string MethodName { get; set; }
    public string ClassName { get; set; }
    public int? LineNumber { get; set; }
    public string FileName { get; set; }
    public string ClientIP { get; set; }
    public string UserAgent { get; set; }
    public string RequestUrl { get; set; }
    public string HttpMethod { get; set; }
    public long? DurationMs { get; set; }
    public int? StatusCode { get; set; }
    public bool IsProcessed { get; set; }
    public string AdminNotes { get; set; }
    public string MessageHash { get; set; }
    public int OccurrenceCount { get; set; }
    public DateTime? LastOccurrence { get; set; }
    public int Id { get; set; }
    public bool Active { get; set; }
    public DateTime CreatedOn { get; set; }
    public string CreatedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
    public string ModifiedBy { get; set; }
}