// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using FluentValidation;
using CodeCraft.NET.Application.CQRS.Base.Features;
using CodeCraft.NET.Application.CQRS.Features.LogEntries.Commands.Update;

namespace CodeCraft.NET.Application.CQRS.Features.LogEntries.Validators
{
    public partial class LogEntryUpdateValidator : BaseValidator<LogEntryUpdate>
    {
        public LogEntryUpdateValidator()
        {
            RuleFor(x => x.Id).GreaterThan(0);
            RuleFor(x => x.Timestamp).NotEmpty();
            RuleFor(x => x.Message).NotEmpty();
            RuleFor(x => x.Category).NotEmpty();
            RuleFor(x => x.Component).NotEmpty();
            RuleFor(x => x.Exception).NotEmpty();
            RuleFor(x => x.StackTrace).NotEmpty();
            RuleFor(x => x.AdditionalData).NotEmpty();
            RuleFor(x => x.CorrelationId).NotEmpty();
            RuleFor(x => x.SessionId).NotEmpty();
            RuleFor(x => x.UserId).NotEmpty();
            RuleFor(x => x.MethodName).NotEmpty();
            RuleFor(x => x.ClassName).NotEmpty();
            RuleFor(x => x.FileName).NotEmpty();
            RuleFor(x => x.ClientIP).NotEmpty();
            RuleFor(x => x.UserAgent).NotEmpty();
            RuleFor(x => x.RequestUrl).NotEmpty();
            RuleFor(x => x.HttpMethod).NotEmpty();
            RuleFor(x => x.AdminNotes).NotEmpty();
            RuleFor(x => x.MessageHash).NotEmpty();
            RuleFor(x => x.OccurrenceCount).GreaterThan(0);
            RuleFor(x => x.CreatedOn).NotEmpty();
            RuleFor(x => x.CreatedBy).NotEmpty();
            RuleFor(x => x.ModifiedBy).NotEmpty();
        }
    }
}
