// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Application.CQRS.Base.Specifications;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Specifications.LogEntries;

public partial class LogEntrySpecification : BaseSpecification<LogEntry>
{
    public LogEntrySpecification(LogEntrySpecificationParams parameters)
        : base(x =>
            string.IsNullOrWhiteSpace(parameters.Search) 
            || (x.Message != null && x.Message.ToLower().Contains(parameters.Search.ToLower()))
            || (x.Category != null && x.Category.ToLower().Contains(parameters.Search.ToLower()))
            || (x.Component != null && x.Component.ToLower().Contains(parameters.Search.ToLower()))
            || (x.Exception != null && x.Exception.ToLower().Contains(parameters.Search.ToLower()))
            || (x.StackTrace != null && x.StackTrace.ToLower().Contains(parameters.Search.ToLower()))
            || (x.AdditionalData != null && x.AdditionalData.ToLower().Contains(parameters.Search.ToLower()))
            || (x.CorrelationId != null && x.CorrelationId.ToLower().Contains(parameters.Search.ToLower()))
            || (x.SessionId != null && x.SessionId.ToLower().Contains(parameters.Search.ToLower()))
            || (x.UserId != null && x.UserId.ToLower().Contains(parameters.Search.ToLower()))
            || (x.MethodName != null && x.MethodName.ToLower().Contains(parameters.Search.ToLower()))
            || (x.ClassName != null && x.ClassName.ToLower().Contains(parameters.Search.ToLower()))
            || (x.FileName != null && x.FileName.ToLower().Contains(parameters.Search.ToLower()))
            || (x.ClientIP != null && x.ClientIP.ToLower().Contains(parameters.Search.ToLower()))
            || (x.UserAgent != null && x.UserAgent.ToLower().Contains(parameters.Search.ToLower()))
            || (x.RequestUrl != null && x.RequestUrl.ToLower().Contains(parameters.Search.ToLower()))
            || (x.HttpMethod != null && x.HttpMethod.ToLower().Contains(parameters.Search.ToLower()))
            || (x.AdminNotes != null && x.AdminNotes.ToLower().Contains(parameters.Search.ToLower()))
            || (x.MessageHash != null && x.MessageHash.ToLower().Contains(parameters.Search.ToLower()))
            || (x.CreatedBy != null && x.CreatedBy.ToLower().Contains(parameters.Search.ToLower()))
            || (x.ModifiedBy != null && x.ModifiedBy.ToLower().Contains(parameters.Search.ToLower()))
        )
    {
        Paging(parameters.PageSize * (parameters.PageIndex - 1), parameters.PageSize);

        if (!string.IsNullOrEmpty(parameters.Sort))
        {
            switch (parameters.Sort.ToLower())
            {
                case "idAsc":
                    AddOrderBy(x => x.Id);
                    break;
                case "idDesc":
                    AddOrderByDescending(x => x.Id);
                    break;
                default:
                    AddOrderBy(x => x.Id);
                    break;
            }
        }
    }
}
