// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Application.CQRS.Features.LogSummaries.Commands.Create;
using CodeCraft.NET.Application.CQRS.Features.LogSummaries.Commands.Delete;
using CodeCraft.NET.Application.CQRS.Features.LogSummaries.Commands.Update;
using CodeCraft.NET.Application.CQRS.Features.LogSummaries.Queries.GetLogSummaryById;
using CodeCraft.NET.Application.CQRS.Features.LogSummaries.Queries.GetLogSummaryWithRelated;
using CodeCraft.NET.Application.DTOs.Custom.LogSummaries;
using CodeCraft.NET.Application.DTOs.LogSummaries;
using CodeCraft.NET.Services.Base;
using CodeCraft.NET.Services.Models;
using MediatR;
using Microsoft.Extensions.Logging;


namespace CodeCraft.NET.Services.Services
{
    /// <summary>
    /// Service for LogSummary operations using CQRS pattern.
    /// Provides CRUD operations with logging and error handling.
    /// </summary>
    public partial class LogSummaryService : BaseEntityService<LogSummaryCreate, LogSummaryUpdate, LogSummaryDto, LogSummaryWithRelatedDto>
    {
        public LogSummaryService(IMediator mediator, ILogger<LogSummaryService> logger) 
            : base(mediator, logger, "LogSummary")
        {
        }

        protected override object CreateDeleteCommand(int id)
        {
            return new LogSummaryDelete { Id = id };
        }

        protected override object CreateGetByIdQuery(int id)
        {
            return new GetLogSummaryByIdQuery { Id = id };
        }

        protected override object CreateGetWithRelatedQuery(int id)
        {
            return new GetLogSummaryWithRelatedQuery { Id = id };
        }
    }
}