// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using Microsoft.VisualStudio.TestTools.UnitTesting;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using CodeCraft.NET.Infrastructure.Persistence;
using CodeCraft.NET.Domain.Model;
using CodeCraft.NET.Domain.Model;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Test.Infrastructure.Persistence
{
    [TestClass]
    public class DbContextTests
    {
        private ApplicationDbContext _context = null!;

        [TestInitialize]
        public void Setup()
        {
            var options = new DbContextOptionsBuilder<ApplicationDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            _context = new ApplicationDbContext(options);
        }

        [TestCleanup]
        public void Cleanup()
        {
            _context.Dispose();
        }

        #region DbSet Tests

        [TestMethod]
        public void LogConfigurations_DbSet_ShouldNotBeNull()
        {
            // Assert
            _context.LogConfigurations.Should().NotBeNull();
        }

        [TestMethod]
        public void LogConfigurations_DbSet_ShouldBeQueryable()
        {
            // Act & Assert
            var query = _context.LogConfigurations.AsQueryable();
            query.Should().NotBeNull();
        }

        [TestMethod]
        public void LogEntries_DbSet_ShouldNotBeNull()
        {
            // Assert
            _context.LogEntries.Should().NotBeNull();
        }

        [TestMethod]
        public void LogEntries_DbSet_ShouldBeQueryable()
        {
            // Act & Assert
            var query = _context.LogEntries.AsQueryable();
            query.Should().NotBeNull();
        }

        [TestMethod]
        public void LogSummaries_DbSet_ShouldNotBeNull()
        {
            // Assert
            _context.LogSummaries.Should().NotBeNull();
        }

        [TestMethod]
        public void LogSummaries_DbSet_ShouldBeQueryable()
        {
            // Act & Assert
            var query = _context.LogSummaries.AsQueryable();
            query.Should().NotBeNull();
        }

        #endregion

        #region Database Connection Tests

        [TestMethod]
        public async Task Database_CanConnect_ShouldReturnTrue()
        {
            // Act
            var canConnect = await _context.Database.CanConnectAsync();

            // Assert
            canConnect.Should().BeTrue();
        }

        [TestMethod]
        public void Database_IsInMemory_ShouldBeTrue()
        {
            // Act
            var isInMemory = _context.Database.IsInMemory();

            // Assert
            isInMemory.Should().BeTrue();
        }

        #endregion

        #region SaveChanges Tests

        [TestMethod]
        public async Task SaveChangesAsync_WithoutChanges_ShouldReturnZero()
        {
            // Act
            var result = await _context.SaveChangesAsync();

            // Assert
            result.Should().Be(0);
        }

        #endregion

        #region Model Validation Tests

        [TestMethod]
        public void Model_ShouldHaveAllExpectedEntities()
        {
            // Arrange
            var model = _context.Model;
            var expectedEntityTypes = new[]
            {
                typeof(LogConfiguration),
                typeof(LogEntry),
                typeof(LogSummary),
            };

            // Act & Assert
            foreach (var expectedType in expectedEntityTypes)
            {
                var entityType = model.FindEntityType(expectedType);
                entityType.Should().NotBeNull($"Entity type {expectedType.Name} should be configured in the model");
            }
        }

        #endregion
    }
}