// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Application.Contracts.Persistence.Base;

namespace CodeCraft.NET.Application.Contracts.Persistence;

public partial interface ICodeCraftUnitOfWork : IUnitOfWork
{
}
