// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.DTOs.LogConfigurations
{
    public class LogConfigurationDto
    {
        public int Id { get; set; }
        public string Component { get; set; }
        public SystemComponent ComponentCategory { get; set; }
        public string NamespacePath { get; set; }
        public LogLevel MinimumLevel { get; set; }
        public bool IsEnabled { get; set; }
        public LogDestination EnabledDestinations { get; set; }
        public bool LogToDatabase { get; set; }
        public bool LogToFile { get; set; }
        public bool LogToConsole { get; set; }
        public string LogFilePath { get; set; }
        public string LogFormat { get; set; }
        public int RetentionDays { get; set; }
        public int MaxFileSizeMB { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public bool Active { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}