// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using AutoMapper;
using CodeCraft.NET.Application.Contracts.Persistence;
using CodeCraft.NET.Application.CQRS.Base.Features;
using CodeCraft.NET.Domain.Model;
using Microsoft.Extensions.Logging;

namespace CodeCraft.NET.Application.CQRS.Features.LogSummaries.Commands.Create;

internal partial class LogSummaryCreateHandler : CreateHandler<LogSummaryCreate, LogSummary, ICodeCraftUnitOfWork>
{
	public LogSummaryCreateHandler(ICodeCraftUnitOfWork unitOfWork, IMapper mapper, ILogger<LogSummaryCreateHandler> logger)
		: base(unitOfWork, mapper, logger)
	{
	}
}