// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Application.CQRS.Base.Specifications;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Specifications.LogConfigurations;

public partial class LogConfigurationWithRelated : BaseSpecification<LogConfiguration>
{
    public LogConfigurationWithRelated()
    {
        AddInclude(x => x.ComponentCategory);
        AddInclude(x => x.MinimumLevel);
        AddInclude(x => x.EnabledDestinations);
    }
}
