// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using CodeCraft.NET.Application.CQRS.Base.Specifications;

namespace CodeCraft.NET.Application.CQRS.Specifications.LogConfigurations;

public partial class LogConfigurationSpecificationParams : SpecificationParams
{
}
