// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using AutoMapper;
using CodeCraft.NET.Domain.Model;

using CodeCraft.NET.Application.CQRS.Features.Users.Commands.Create;
using CodeCraft.NET.Application.CQRS.Features.Users.Commands.Update;


namespace CodeCraft.NET.Application.Mapping
{
    public partial class MappingProfile : Profile
    {
        public MappingProfile()
        {
            ConfigureGeneratedMappings();
            ConfigureCustomMappings();
        }

        private void ConfigureGeneratedMappings()
        {
        
                CreateMap<User, UserCreate>().ReverseMap();
                CreateMap<User, UserUpdate>().ReverseMap();
                
        }

        partial void ConfigureCustomMappings();
    }
}
