// <auto-generated>
//     This code was generated by CodeCraft.NET.Generator.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using AutoMapper;

namespace CodeCraft.NET.Application.Mapping
{
    public partial class MappingProfile : Profile
    {
        public MappingProfile()
        {
            ConfigureGeneratedMappings();
            ConfigureCustomMappings();
        }

        private void ConfigureGeneratedMappings()
        {
        }

        partial void ConfigureCustomMappings();
    }
}
