// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using MediatR;

namespace CodeCraft.NET.Application.CQRS.Features.LogSummaries.Commands.Delete;

public partial class LogSummaryDelete : IRequest<bool>
{
    public int Id { get; set; }
}