// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using AutoMapper;
using CodeCraft.NET.Application.Contracts.Persistence.Repositories;
using CodeCraft.NET.Application.CQRS.Base.Specifications;
using CodeCraft.NET.Application.CQRS.Features.LogSummaries.Queries.GetLogSummaryWithRelated;
using CodeCraft.NET.Application.DTOs.Custom.LogSummaries;
using CodeCraft.NET.Domain.Model;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;


namespace CodeCraft.NET.Test.Application.CQRS.Features.LogSummaries.Queries
{
    [TestClass]
    public class GetLogSummaryWithRelatedHandlerTests
    {
        private Mock<ILogSummaryRepository> _repositoryMock = null!;
        private Mock<IMapper> _mapperMock = null!;
        private GetLogSummaryWithRelatedHandler _handler = null!;

        [TestInitialize]
        public void Setup()
        {
            _repositoryMock = new Mock<ILogSummaryRepository>();
            _mapperMock = new Mock<IMapper>();

            _handler = new GetLogSummaryWithRelatedHandler(_repositoryMock.Object, _mapperMock.Object);
        }

        [TestCleanup]
        public void Cleanup()
        {
            _repositoryMock.Reset();
            _mapperMock.Reset();
        }

        [TestMethod]
        public async Task Handle_ExistingEntity_ReturnsWithRelatedDto()
        {
            // Arrange
            var query = new GetLogSummaryWithRelatedQuery { Id = 1 };
            var entity = new LogSummary { Id = 1 };
            var dto = new LogSummaryWithRelatedDto { Id = 1 };

            _repositoryMock.Setup(x => x.GetByIdWithSpecifications(It.IsAny<ISpecification<LogSummary>>()))
                .ReturnsAsync(entity);

            _mapperMock.Setup(x => x.Map<LogSummaryWithRelatedDto>(entity))
                .Returns(dto);

            // Act
            var result = await _handler.Handle(query, CancellationToken.None);

            // Assert
            result.Should().NotBeNull();
            result.Should().BeEquivalentTo(dto);

            _repositoryMock.Verify(x => x.GetByIdWithSpecifications(It.IsAny<ISpecification<LogSummary>>()), Times.Once);
            _mapperMock.Verify(x => x.Map<LogSummaryWithRelatedDto>(entity), Times.Once);
        }

        [TestMethod]
        public async Task Handle_NonExistentEntity_ReturnsNull()
        {
            // Arrange
            var query = new GetLogSummaryWithRelatedQuery { Id = 999 };

            _repositoryMock.Setup(x => x.GetByIdWithSpecifications(It.IsAny<ISpecification<LogSummary>>()))
                .ReturnsAsync((LogSummary?)null);

            // Act
            var result = await _handler.Handle(query, CancellationToken.None);

            // Assert
            result.Should().BeNull();

            _repositoryMock.Verify(x => x.GetByIdWithSpecifications(It.IsAny<ISpecification<LogSummary>>()), Times.Once);
            _mapperMock.Verify(x => x.Map<LogSummaryWithRelatedDto>(It.IsAny<LogSummary>()), Times.Never);
        }

        [TestMethod]
        public async Task Handle_RepositoryThrowsException_PropagatesException()
        {
            // Arrange
            var query = new GetLogSummaryWithRelatedQuery { Id = 1 };

            _repositoryMock.Setup(x => x.GetByIdWithSpecifications(It.IsAny<ISpecification<LogSummary>>()))
                .ThrowsAsync(new Exception("Database error"));

            // Act & Assert
            await Assert.ThrowsExceptionAsync<Exception>(() => 
                _handler.Handle(query, CancellationToken.None));

            _repositoryMock.Verify(x => x.GetByIdWithSpecifications(It.IsAny<ISpecification<LogSummary>>()), Times.Once);
        }

        [TestMethod]
        public async Task Handle_MappingThrowsException_PropagatesException()
        {
            // Arrange
            var query = new GetLogSummaryWithRelatedQuery { Id = 1 };
            var entity = new LogSummary { Id = 1 };

            _repositoryMock.Setup(x => x.GetByIdWithSpecifications(It.IsAny<ISpecification<LogSummary>>()))
                .ReturnsAsync(entity);

            _mapperMock.Setup(x => x.Map<LogSummaryWithRelatedDto>(entity))
                .Throws(new Exception("Mapping failed"));

            // Act & Assert
            await Assert.ThrowsExceptionAsync<Exception>(() => 
                _handler.Handle(query, CancellationToken.None));

            _repositoryMock.Verify(x => x.GetByIdWithSpecifications(It.IsAny<ISpecification<LogSummary>>()), Times.Once);
            _mapperMock.Verify(x => x.Map<LogSummaryWithRelatedDto>(entity), Times.Once);
        }
    }
}