using Scriban;
using System.Text.Json;

namespace CodeCraft.NET.Generator.Models
{
	public class CodeCraftConfig
	{
		public DataBaseConfig DataBaseConfig { get; set; } = new DataBaseConfig();
		public MauiConfig MauiConfig { get; set; } = new();
		public Files Files { get; set; } = new Files();
		public Folders Folders { get; set; } = new Folders();
		public ProjectNames ProjectNames { get; set; } = new ProjectNames();
		public Templates Templates { get; set; } = new Templates();

		private static CodeCraftConfig? _instance;
		public static CodeCraftConfig Instance => _instance ??= LoadConfig();

		private static CodeCraftConfig LoadConfig()
		{
			var locations = new[]
			{
				Path.Combine(AppContext.BaseDirectory, "codecraft.config.json"),
				// 2. In the current working directory
				Path.Combine(Directory.GetCurrentDirectory(), "codecraft.config.json"),
				// 3. In the application domain base directory
				Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "codecraft.config.json"),
				// 4. Just the filename (search in PATH)
				"codecraft.config.json",
				// 5. In the solution root (go up from bin directories)
				Path.Combine(FindSolutionRoot(), "codecraft.config.json"),
				// 6. In the Generator directory specifically within the solution
				Path.Combine(FindSolutionRoot(), "CodeCraft.NET.Generator", "codecraft.config.json"),
				// 7. Search in parent directory (for projects generated by template)
				Path.Combine(FindSolutionRoot(), "*Generator", "codecraft.config.json")
			};

			string? configPath = null;
			
			// Search using wildcards for projects with dynamic names
			foreach (var location in locations)
			{
				if (location.Contains("*Generator"))
				{
					var solutionRootPath = FindSolutionRoot();
					var generatorDirs = Directory.GetDirectories(solutionRootPath, "*Generator", SearchOption.TopDirectoryOnly);
					foreach (var genDir in generatorDirs)
					{
						var configFile = Path.Combine(genDir, "codecraft.config.json");
						if (File.Exists(configFile))
						{
							configPath = configFile;
							break;
						}
					}
					if (configPath != null) break;
				}
				else if (File.Exists(location))
				{
					configPath = location;
					break;
				}
			}
			
			if (configPath == null)
			{
				Console.WriteLine("Searching for codecraft.config.json in these locations:");
				foreach (var location in locations.Where(l => !l.Contains("*Generator")))
				{
					Console.WriteLine($"   {location}");
				}
				
				// Also show found Generator directories
				var solutionRootPath = FindSolutionRoot();
				var generatorDirs = Directory.GetDirectories(solutionRootPath, "*Generator", SearchOption.TopDirectoryOnly);
				if (generatorDirs.Any())
				{
					Console.WriteLine("   Generator directories found:");
					foreach (var genDir in generatorDirs)
					{
						var configFile = Path.Combine(genDir, "codecraft.config.json");
						Console.WriteLine($"   {configFile}");
					}
				}
				
				throw new FileNotFoundException("Configuration file 'codecraft.config.json' not found.");
			}

			Console.WriteLine($"Found configuration file: {configPath}");
			var json = File.ReadAllText(configPath);
			var data = JsonSerializer.Deserialize<CodeCraftConfig>(json, new JsonSerializerOptions
			{
				PropertyNameCaseInsensitive = true
			}) ?? throw new InvalidOperationException("Invalid config format.");

			// SAFETY VALIDATION: Ensure we're working in the intended solution
			var configDirectory = Path.GetDirectoryName(configPath);
			var solutionRoot = FindSolutionRoot();
			
			Console.WriteLine($"Configuration directory: {configDirectory}");
			Console.WriteLine($"Solution root detected: {solutionRoot}");
			
			// Warn if the config and solution don't seem to match
			if (configDirectory != null && !solutionRoot.StartsWith(configDirectory.Substring(0, Math.Min(configDirectory.Length, solutionRoot.Length))))
			{
				Console.WriteLine($"WARNING: Configuration and solution paths seem mismatched!");
				Console.WriteLine($"   Config: {configDirectory}");
				Console.WriteLine($"   Solution: {solutionRoot}");
				Console.WriteLine($"   Ensure you're running from the correct directory.");
			}

			return data;
		}

		private static string FindSolutionRoot()
		{
			// Start from the current directory (where the generator is executed)
			var currentDir = new DirectoryInfo(Directory.GetCurrentDirectory());
			
			// First, try to find the solution file from current directory
			while (currentDir != null)
			{
				if (currentDir.GetFiles("*.sln").Any())
				{
					return currentDir.FullName;
				}
				currentDir = currentDir.Parent;
			}
			
			// Fallback: try from AppContext.BaseDirectory (bin/Debug/net9.0)
			currentDir = new DirectoryInfo(AppContext.BaseDirectory);
			
			// Navigate up from bin/Debug/net9.0 to solution root
			while (currentDir != null)
			{
				if (currentDir.GetFiles("*.sln").Any())
				{
					return currentDir.FullName;
				}
				currentDir = currentDir.Parent;
			}
			
			// SAFE FALLBACK: Use current directory instead of hardcoded path
			var currentDirectory = Directory.GetCurrentDirectory();
			Console.WriteLine($"Warning: Could not find .sln file. Using current directory: {currentDirectory}");
			Console.WriteLine("   Make sure you're running the generator from within the solution directory.");
			
			return currentDirectory;
		}

		// Public method to access solution root
		public string GetSolutionRoot() => FindSolutionRoot();

		// Convenience methods to get paths
		public string GetSolutionRelativePath(string projectName)
		{
			var solutionRoot = FindSolutionRoot();
			var result = Path.Combine(solutionRoot, projectName);
			
			// SAFETY CHECK: Ensure we're not accidentally working in another solution
			if (!Directory.Exists(solutionRoot))
			{
				throw new DirectoryNotFoundException($"Solution root directory does not exist: {solutionRoot}");
			}
			
			// SAFETY CHECK: Verify this looks like our solution
			var solutionFiles = Directory.GetFiles(solutionRoot, "*.sln");
			if (!solutionFiles.Any())
			{
				Console.WriteLine($"Warning: No .sln files found in {solutionRoot}");
				Console.WriteLine("   This might not be the correct solution directory.");
			}
			
			return result;
		}

		public string PluralizeName(string name)
		{
			if (name.EndsWith('y') && name.Length > 1 && !"aeiou".Contains(name[^2]))
				return name[..^1] + "ies";
			if (name.EndsWith('s') || name.EndsWith('x') || name.EndsWith('z') || name.EndsWith("ch") || name.EndsWith("sh"))
				return name + "es";
			return name + "s";
		}
	}
}