// <auto-generated>
//     This code was generated by CodeCraft.NET Generator.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using Microsoft.Extensions.DependencyInjection;
using CodeCraft.NET.MAUI.Interfaces;
using CodeCraft.NET.MAUI.Services;

namespace CodeCraft.NET.MAUI
{
    public static class MauiServiceRegistration
    {
        /// <summary>
        /// Registers all MAUI-specific services including ViewModels and Pages
        /// </summary>
        public static IServiceCollection AddMauiServices(this IServiceCollection services)
        {
            // Common Services
            services.AddSingleton<IDialogService, DialogService>();
            services.AddSingleton<INavigationService, NavigationService>();

            return services;
        }
    }
}