// <auto-generated>
//     This code was generated by CodeCraft.NET Generator.
//     Manual changes to this file may be overwritten.
// </auto-generated>

namespace CodeCraft.NET.MAUI
{
    public static class ShellRouting
    {
        /// <summary>
        /// Registers all Shell routes for navigation
        /// </summary>
        public static void RegisterRoutes()
        {

        }
    }
}