// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using FluentValidation;
using CodeCraft.NET.Application.CQRS.Base.Features;

namespace CodeCraft.NET.Application.CQRS.Features.Users.Commands.Create
{
    public partial class UserCreateValidator : AbstractValidator<UserCreate>
    {
        public UserCreateValidator()
        {
            RuleFor(x => x.Email).NotEmpty();
            RuleFor(x => x.FullName).NotEmpty();
            RuleFor(x => x.IdentityId).NotEmpty();
            RuleFor(x => x.CreatedBy).NotEmpty();
            RuleFor(x => x.LastModifiedBy).NotEmpty();
        }
    }
}
