// <auto-generated>
//     This code was generated by CodeCraft.NET.
//     Manual changes to this file may be overwritten.
// </auto-generated>

using Microsoft.Extensions.Logging;
using AutoMapper;
using CodeCraft.NET.Application.CQRS.Base.Features;
using CodeCraft.NET.Application.Contracts.Persistence;
using CodeCraft.NET.Domain.Model;

namespace CodeCraft.NET.Application.CQRS.Features.Users.Commands.Create;

internal partial class UserCreateHandler : CreateHandler<UserCreate, User, ICodeCraftUnitOfWork>
{
	public UserCreateHandler(ICodeCraftUnitOfWork unitOfWork, IMapper mapper, ILogger<UserCreateHandler> logger)
		: base(unitOfWork, mapper, logger)
	{
	}
}